{% set name = "cachetools" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cachetools-{{ version }}.tar.gz
  sha256: 38b328c0889450f05f5e120f56ab68c8abaf424e1275522b138ffc93253f7e32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - cachetools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tkem/cachetools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extensible memoizing collections and decorators
  description: |
    This module provides various memoizing collections and decorators, including variants of the Python 3 Standard Library @lru_cache function decorator.
  doc_url: http://pythonhosted.org/cachetools/
  dev_url: https://github.com/tkem/cachetools

extra:
  recipe-maintainers:
    - rxm7706
    - maartenbreddels
    - marcelotrevisani
