{% set name = "cachetools" %}
{% set version = "4.0.0" %}
{% set sha256 = "9a52dd97a85f257f4e4127f15818e71a0c7899f121b34591fcc1173ea79a0198" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - cachetools

about:
  home: https://github.com/tkem/cachetools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Extensible memoizing collections and decorators'

  description: |
    This module provides various memoizing collections and decorators, including variants of the Python 3 Standard Library @lru_cache function decorator.
  doc_url: http://pythonhosted.org/cachetools/
  dev_url: https://github.com/tkem/cachetools

extra:
  recipe-maintainers:
    - maartenbreddels
