{% set name = "cachetools" %}
{% set version = "6.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cachetools-{{ version }}.tar.gz
  sha256: 3f391e4bd8f8bf0931169baf7456cc822705f4e2a31f840d218f445b9a854201

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - cachetools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tkem/cachetools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extensible memoizing collections and decorators
  description: |
    This module provides various memoizing collections and decorators, including variants of the Python 3 Standard Library @lru_cache function decorator.
  doc_url: http://pythonhosted.org/cachetools/
  dev_url: https://github.com/tkem/cachetools

extra:
  recipe-maintainers:
    - rxm7706
    - maartenbreddels
    - marcelotrevisani
